title: Xuan Tran # your name (or website title) here
logo: "/images/picture-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  MSc. Information & Service Management <br> Specialization: Business Analytics <br> Aalto University</font>
  <br><br>
  Seeking Data Analytics opportunities.  
  <br><br>
  <a href="https://www.linkedin.com/in/xuan-tran-614737b0/">View My LinkedIn Profile</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-0C3VNS6QZM # your Google Analytics tracking ID here
